<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170720224740 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE discipline_has_laboratoire DROP FOREIGN KEY fk_discipline_has_laboratoire_discipline1');
        $this->addSql('ALTER TABLE discipline_has_laboratoire DROP FOREIGN KEY fk_discipline_has_laboratoire_laboratoire1');
        $this->addSql('DROP INDEX idx_ac8c4dbca5522701 ON discipline_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_A4BDA9DA5522701 ON discipline_has_laboratoire (discipline_id)');
        $this->addSql('DROP INDEX idx_ac8c4dbcb65fa4a ON discipline_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_A4BDA9D76E2617B ON discipline_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE discipline_has_laboratoire ADD CONSTRAINT fk_discipline_has_laboratoire_discipline1 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE discipline_has_laboratoire ADD CONSTRAINT fk_discipline_has_laboratoire_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale DROP FOREIGN KEY fk_discipline_has_ecole_doctorale_discipline1');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale DROP FOREIGN KEY fk_discipline_has_ecole_doctorale_ecole_doctorale1');
        $this->addSql('DROP INDEX idx_c5488024a5522701 ON discipline_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_A39BB523A5522701 ON discipline_has_ecole_doctorale (discipline_id)');
        $this->addSql('DROP INDEX idx_c5488024bab47356 ON discipline_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_A39BB523D5F8595C ON discipline_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale ADD CONSTRAINT fk_discipline_has_ecole_doctorale_discipline1 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale ADD CONSTRAINT fk_discipline_has_ecole_doctorale_ecole_doctorale1 FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire DROP FOREIGN KEY fk_etablissement_has_laboratoire_etablissement1');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire DROP FOREIGN KEY fk_etablissement_has_laboratoire_laboratoire1');
        $this->addSql('DROP INDEX idx_cc521a16ff631228 ON etablissement_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_F5F858C9FF631228 ON etablissement_has_laboratoire (etablissement_id)');
        $this->addSql('DROP INDEX idx_cc521a16b65fa4a ON etablissement_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_F5F858C976E2617B ON etablissement_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire ADD CONSTRAINT fk_etablissement_has_laboratoire_etablissement1 FOREIGN KEY (etablissement_id) REFERENCES etablissement (etablissement_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire ADD CONSTRAINT fk_etablissement_has_laboratoire_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale DROP FOREIGN KEY FK_D9DBFCD9BAB47356');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale DROP FOREIGN KEY fk_etablissement_has_ED_etablissement1');
        $this->addSql('DROP INDEX idx_7731f8b3ff631228 ON etablissement_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_E7AFF0CEFF631228 ON etablissement_has_ecole_doctorale (etablissement_id)');
        $this->addSql('DROP INDEX idx_7731f8b3bab47356 ON etablissement_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_E7AFF0CED5F8595C ON etablissement_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale ADD CONSTRAINT FK_D9DBFCD9BAB47356 FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale ADD CONSTRAINT fk_etablissement_has_ED_etablissement1 FOREIGN KEY (etablissement_id) REFERENCES etablissement (etablissement_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE participant_has_formation DROP FOREIGN KEY fk_participant_has_formation_formation1');
        $this->addSql('ALTER TABLE participant_has_formation DROP FOREIGN KEY fk_participant_has_formation_participant1');
        $this->addSql('DROP INDEX idx_464e5dc25200282e ON participant_has_formation');
        $this->addSql('CREATE INDEX IDX_E41DAB6C5200282E ON participant_has_formation (formation_id)');
        $this->addSql('DROP INDEX idx_464e5dc26a99f74a ON participant_has_formation');
        $this->addSql('CREATE INDEX IDX_E41DAB6C9D1C3019 ON participant_has_formation (participant_id)');
        $this->addSql('ALTER TABLE participant_has_formation ADD CONSTRAINT fk_participant_has_formation_formation1 FOREIGN KEY (formation_id) REFERENCES formation (formation_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE participant_has_formation ADD CONSTRAINT fk_participant_has_formation_participant1 FOREIGN KEY (participant_id) REFERENCES participant (participant_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE laboratoire DROP FOREIGN KEY FK_9367435C9C347F1C');
        $this->addSql('DROP INDEX idx_9367435c9c347f1c ON laboratoire');
        $this->addSql('CREATE INDEX IDX_C4AD03C39C347F1C ON laboratoire (type_thesaurus)');
        $this->addSql('ALTER TABLE laboratoire ADD CONSTRAINT FK_9367435C9C347F1C FOREIGN KEY (type_thesaurus) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE laboratoire_has_theme DROP FOREIGN KEY FK_827F9609B65FA4A');
        $this->addSql('DROP INDEX idx_827f9609b65fa4a ON laboratoire_has_theme');
        $this->addSql('CREATE INDEX IDX_827F960976E2617B ON laboratoire_has_theme (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_theme ADD CONSTRAINT FK_827F9609B65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE participant_has_laboratoire DROP FOREIGN KEY fk_participant_has_laboratoire_laboratoire1');
        $this->addSql('ALTER TABLE participant_has_laboratoire DROP FOREIGN KEY fk_participant_has_laboratoire_participant1');
        $this->addSql('DROP INDEX idx_7b597030b65fa4a ON participant_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_63D55B7C76E2617B ON participant_has_laboratoire (laboratoire_id)');
        $this->addSql('DROP INDEX idx_7b5970306a99f74a ON participant_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_63D55B7C9D1C3019 ON participant_has_laboratoire (participant_id)');
        $this->addSql('ALTER TABLE participant_has_laboratoire ADD CONSTRAINT fk_participant_has_laboratoire_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE participant_has_laboratoire ADD CONSTRAINT fk_participant_has_laboratoire_participant1 FOREIGN KEY (participant_id) REFERENCES participant (participant_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE laboratoire_has_tag DROP FOREIGN KEY FK_B73CE04BB65FA4A');
        $this->addSql('ALTER TABLE laboratoire_has_tag DROP FOREIGN KEY FK_B73CE04BBAD26311');
        $this->addSql('DROP INDEX idx_b73ce04bb65fa4a ON laboratoire_has_tag');
        $this->addSql('CREATE INDEX IDX_3FD71D6676E2617B ON laboratoire_has_tag (laboratoire_id)');
        $this->addSql('DROP INDEX idx_b73ce04bbad26311 ON laboratoire_has_tag');
        $this->addSql('CREATE INDEX IDX_3FD71D66BAD26311 ON laboratoire_has_tag (tag_id)');
        $this->addSql('ALTER TABLE laboratoire_has_tag ADD CONSTRAINT FK_B73CE04BB65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_tag ADD CONSTRAINT FK_B73CE04BBAD26311 FOREIGN KEY (tag_id) REFERENCES tag (tag_id)');
        $this->addSql('ALTER TABLE laboratoire_has_formation DROP FOREIGN KEY fk_laboratoire_has_formation_formation1');
        $this->addSql('ALTER TABLE laboratoire_has_formation DROP FOREIGN KEY fk_laboratoire_has_formation_laboratoire1');
        $this->addSql('DROP INDEX idx_df3346d9b65fa4a ON laboratoire_has_formation');
        $this->addSql('CREATE INDEX IDX_3AFD48DC76E2617B ON laboratoire_has_formation (laboratoire_id)');
        $this->addSql('DROP INDEX idx_df3346d95200282e ON laboratoire_has_formation');
        $this->addSql('CREATE INDEX IDX_3AFD48DC5200282E ON laboratoire_has_formation (formation_id)');
        $this->addSql('ALTER TABLE laboratoire_has_formation ADD CONSTRAINT fk_laboratoire_has_formation_formation1 FOREIGN KEY (formation_id) REFERENCES formation (formation_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE laboratoire_has_formation ADD CONSTRAINT fk_laboratoire_has_formation_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE laboratoire_has_cnu DROP FOREIGN KEY FK_DA743839A5522701');
        $this->addSql('ALTER TABLE laboratoire_has_cnu DROP FOREIGN KEY FK_DA743839B65FA4A');
        $this->addSql('DROP INDEX idx_da743839b65fa4a ON laboratoire_has_cnu');
        $this->addSql('CREATE INDEX IDX_529FC51476E2617B ON laboratoire_has_cnu (laboratoire_id)');
        $this->addSql('DROP INDEX idx_da743839a5522701 ON laboratoire_has_cnu');
        $this->addSql('CREATE INDEX IDX_529FC514A5522701 ON laboratoire_has_cnu (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_cnu ADD CONSTRAINT FK_DA743839A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_cnu ADD CONSTRAINT FK_DA743839B65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_sise DROP FOREIGN KEY FK_B30960F6A5522701');
        $this->addSql('ALTER TABLE laboratoire_has_sise DROP FOREIGN KEY FK_B30960F6B65FA4A');
        $this->addSql('DROP INDEX idx_b30960f6b65fa4a ON laboratoire_has_sise');
        $this->addSql('CREATE INDEX IDX_F65ED77E76E2617B ON laboratoire_has_sise (laboratoire_id)');
        $this->addSql('DROP INDEX idx_b30960f6a5522701 ON laboratoire_has_sise');
        $this->addSql('CREATE INDEX IDX_F65ED77EA5522701 ON laboratoire_has_sise (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_sise ADD CONSTRAINT FK_B30960F6A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_sise ADD CONSTRAINT FK_B30960F6B65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_hceres DROP FOREIGN KEY FK_D0B16EBEA5522701');
        $this->addSql('ALTER TABLE laboratoire_has_hceres DROP FOREIGN KEY FK_D0B16EBEB65FA4A');
        $this->addSql('DROP INDEX idx_d0b16ebeb65fa4a ON laboratoire_has_hceres');
        $this->addSql('CREATE INDEX IDX_76EE1F8576E2617B ON laboratoire_has_hceres (laboratoire_id)');
        $this->addSql('DROP INDEX idx_d0b16ebea5522701 ON laboratoire_has_hceres');
        $this->addSql('CREATE INDEX IDX_76EE1F85A5522701 ON laboratoire_has_hceres (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_hceres ADD CONSTRAINT FK_D0B16EBEA5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_hceres ADD CONSTRAINT FK_D0B16EBEB65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_equipement DROP FOREIGN KEY fk_laboratoire_has_equipement_equipement1');
        $this->addSql('ALTER TABLE laboratoire_has_equipement DROP FOREIGN KEY fk_laboratoire_has_equipement_laboratoire1');
        $this->addSql('DROP INDEX idx_1cfa71f9b65fa4a ON laboratoire_has_equipement');
        $this->addSql('CREATE INDEX IDX_6C754B7876E2617B ON laboratoire_has_equipement (laboratoire_id)');
        $this->addSql('DROP INDEX idx_1cfa71f9806f0f5c ON laboratoire_has_equipement');
        $this->addSql('CREATE INDEX IDX_6C754B78806F0F5C ON laboratoire_has_equipement (equipement_id)');
        $this->addSql('ALTER TABLE laboratoire_has_equipement ADD CONSTRAINT fk_laboratoire_has_equipement_equipement1 FOREIGN KEY (equipement_id) REFERENCES equipement (equipement_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE laboratoire_has_equipement ADD CONSTRAINT fk_laboratoire_has_equipement_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire DROP FOREIGN KEY ecole_doctorale_has_laboratoire_ibfk_1');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire DROP FOREIGN KEY FK_94FAE651B65FA4A');
        $this->addSql('DROP INDEX idx_94fae651b65fa4a ON ecole_doctorale_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_6C0DB82C76E2617B ON ecole_doctorale_has_laboratoire (laboratoire_id)');
        $this->addSql('DROP INDEX idx_94fae651bab47356 ON ecole_doctorale_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_6C0DB82CD5F8595C ON ecole_doctorale_has_laboratoire (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire ADD CONSTRAINT ecole_doctorale_has_laboratoire_ibfk_1 FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire ADD CONSTRAINT FK_94FAE651B65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_axe DROP FOREIGN KEY FK_D8DF49E42E30CD41');
        $this->addSql('ALTER TABLE laboratoire_has_axe DROP FOREIGN KEY FK_D8DF49E4B65FA4A');
        $this->addSql('DROP INDEX idx_d8df49e4b65fa4a ON laboratoire_has_axe');
        $this->addSql('CREATE INDEX IDX_5034B4C976E2617B ON laboratoire_has_axe (laboratoire_id)');
        $this->addSql('DROP INDEX idx_d8df49e42e30cd41 ON laboratoire_has_axe');
        $this->addSql('CREATE INDEX IDX_5034B4C92E30CD41 ON laboratoire_has_axe (axe_id)');
        $this->addSql('ALTER TABLE laboratoire_has_axe ADD CONSTRAINT FK_D8DF49E42E30CD41 FOREIGN KEY (axe_id) REFERENCES axe (axe_id)');
        $this->addSql('ALTER TABLE laboratoire_has_axe ADD CONSTRAINT FK_D8DF49E4B65FA4A FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE adresse CHANGE `long` lon VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE adresse_has_ufr DROP FOREIGN KEY fk_adresse_has_ufr_adresse1');
        $this->addSql('ALTER TABLE adresse_has_ufr DROP FOREIGN KEY fk_adresse_has_ufr_ufr1');
        $this->addSql('DROP INDEX idx_705b91fbc68be09c ON adresse_has_ufr');
        $this->addSql('CREATE INDEX IDX_BA094DFD4DE7DC5C ON adresse_has_ufr (adresse_id)');
        $this->addSql('DROP INDEX idx_705b91fba469cb09 ON adresse_has_ufr');
        $this->addSql('CREATE INDEX IDX_BA094DFDA469CB09 ON adresse_has_ufr (ufr_id)');
        $this->addSql('ALTER TABLE adresse_has_ufr ADD CONSTRAINT fk_adresse_has_ufr_adresse1 FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_ufr ADD CONSTRAINT fk_adresse_has_ufr_ufr1 FOREIGN KEY (ufr_id) REFERENCES ufr (ufr_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_laboratoire DROP FOREIGN KEY fk_adresse_has_laboratoire_adresse1');
        $this->addSql('ALTER TABLE adresse_has_laboratoire DROP FOREIGN KEY fk_adresse_has_laboratoire_laboratoire1');
        $this->addSql('DROP INDEX idx_478cff80c68be09c ON adresse_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_7B1B58CC4DE7DC5C ON adresse_has_laboratoire (adresse_id)');
        $this->addSql('DROP INDEX idx_478cff80b65fa4a ON adresse_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_7B1B58CC76E2617B ON adresse_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE adresse_has_laboratoire ADD CONSTRAINT fk_adresse_has_laboratoire_adresse1 FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_laboratoire ADD CONSTRAINT fk_adresse_has_laboratoire_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_formation DROP FOREIGN KEY fk_adresse_has_formation_adresse1');
        $this->addSql('ALTER TABLE adresse_has_formation DROP FOREIGN KEY fk_adresse_has_formation_formation1');
        $this->addSql('DROP INDEX idx_1b027d9fc68be09c ON adresse_has_formation');
        $this->addSql('CREATE INDEX IDX_7C62D8654DE7DC5C ON adresse_has_formation (adresse_id)');
        $this->addSql('DROP INDEX idx_1b027d9f5200282e ON adresse_has_formation');
        $this->addSql('CREATE INDEX IDX_7C62D8655200282E ON adresse_has_formation (formation_id)');
        $this->addSql('ALTER TABLE adresse_has_formation ADD CONSTRAINT fk_adresse_has_formation_adresse1 FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_formation ADD CONSTRAINT fk_adresse_has_formation_formation1 FOREIGN KEY (formation_id) REFERENCES formation (formation_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_etablissement DROP FOREIGN KEY fk_adresse_has_etablissement_adresse1');
        $this->addSql('ALTER TABLE adresse_has_etablissement DROP FOREIGN KEY fk_adresse_has_etablissement_etablissement1');
        $this->addSql('DROP INDEX idx_db9f843dc68be09c ON adresse_has_etablissement');
        $this->addSql('CREATE INDEX IDX_5BDC72294DE7DC5C ON adresse_has_etablissement (adresse_id)');
        $this->addSql('DROP INDEX idx_db9f843dff631228 ON adresse_has_etablissement');
        $this->addSql('CREATE INDEX IDX_5BDC7229FF631228 ON adresse_has_etablissement (etablissement_id)');
        $this->addSql('ALTER TABLE adresse_has_etablissement ADD CONSTRAINT fk_adresse_has_etablissement_adresse1 FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_etablissement ADD CONSTRAINT fk_adresse_has_etablissement_etablissement1 FOREIGN KEY (etablissement_id) REFERENCES etablissement (etablissement_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale DROP FOREIGN KEY adresse_has_ecole_doctorale_ibfk_1');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale DROP FOREIGN KEY FK_9AC3772CC68BE09C');
        $this->addSql('DROP INDEX idx_9ac3772cc68be09c ON adresse_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_AF220EF44DE7DC5C ON adresse_has_ecole_doctorale (adresse_id)');
        $this->addSql('DROP INDEX idx_9ac3772cbab47356 ON adresse_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_AF220EF4D5F8595C ON adresse_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale ADD CONSTRAINT adresse_has_ecole_doctorale_ibfk_1 FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale ADD CONSTRAINT FK_9AC3772CC68BE09C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
        $this->addSql('ALTER TABLE participant_has_axe DROP FOREIGN KEY FK_EA8D416B2E30CD41');
        $this->addSql('ALTER TABLE participant_has_axe DROP FOREIGN KEY FK_EA8D416B6A99F74A');
        $this->addSql('DROP INDEX idx_ea8d416b6a99f74a ON participant_has_axe');
        $this->addSql('CREATE INDEX IDX_C2A78CDE9D1C3019 ON participant_has_axe (participant_id)');
        $this->addSql('DROP INDEX idx_ea8d416b2e30cd41 ON participant_has_axe');
        $this->addSql('CREATE INDEX IDX_C2A78CDE2E30CD41 ON participant_has_axe (axe_id)');
        $this->addSql('ALTER TABLE participant_has_axe ADD CONSTRAINT FK_EA8D416B2E30CD41 FOREIGN KEY (axe_id) REFERENCES axe (axe_id)');
        $this->addSql('ALTER TABLE participant_has_axe ADD CONSTRAINT FK_EA8D416B6A99F74A FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale DROP FOREIGN KEY FK_2701BB8C6A99F74A');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale DROP FOREIGN KEY participant_has_ecole_doctorale_ibfk_1');
        $this->addSql('DROP INDEX idx_2701bb8c6a99f74a ON participant_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_F6039CA19D1C3019 ON participant_has_ecole_doctorale (participant_id)');
        $this->addSql('DROP INDEX idx_2701bb8cbab47356 ON participant_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_F6039CA1D5F8595C ON participant_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale ADD CONSTRAINT FK_2701BB8C6A99F74A FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale ADD CONSTRAINT participant_has_ecole_doctorale_ibfk_1 FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE participant_has_tag DROP FOREIGN KEY FK_856EE8C46A99F74A');
        $this->addSql('ALTER TABLE participant_has_tag DROP FOREIGN KEY FK_856EE8C4BAD26311');
        $this->addSql('DROP INDEX idx_856ee8c46a99f74a ON participant_has_tag');
        $this->addSql('CREATE INDEX IDX_AD4425719D1C3019 ON participant_has_tag (participant_id)');
        $this->addSql('DROP INDEX idx_856ee8c4bad26311 ON participant_has_tag');
        $this->addSql('CREATE INDEX IDX_AD442571BAD26311 ON participant_has_tag (tag_id)');
        $this->addSql('ALTER TABLE participant_has_tag ADD CONSTRAINT FK_856EE8C46A99F74A FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_tag ADD CONSTRAINT FK_856EE8C4BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (tag_id)');
        $this->addSql('ALTER TABLE ufr_has_laboratoire DROP FOREIGN KEY fk_ufr_has_laboratoire_laboratoire1');
        $this->addSql('ALTER TABLE ufr_has_laboratoire DROP FOREIGN KEY fk_ufr_has_laboratoire_ufr1');
        $this->addSql('DROP INDEX idx_8b13f098a469cb09 ON ufr_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_F95EE0FFA469CB09 ON ufr_has_laboratoire (ufr_id)');
        $this->addSql('DROP INDEX idx_8b13f098b65fa4a ON ufr_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_F95EE0FF76E2617B ON ufr_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE ufr_has_laboratoire ADD CONSTRAINT fk_ufr_has_laboratoire_laboratoire1 FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE ufr_has_laboratoire ADD CONSTRAINT fk_ufr_has_laboratoire_ufr1 FOREIGN KEY (ufr_id) REFERENCES ufr (ufr_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE valorisation DROP FOREIGN KEY fk_valorisation_adresse1');
        $this->addSql('DROP INDEX fk_valorisation_adresse1_idx ON valorisation');
        $this->addSql('CREATE INDEX fk_valorisation_localisation1_idx ON valorisation (adresse_id)');
        $this->addSql('ALTER TABLE valorisation ADD CONSTRAINT fk_valorisation_adresse1 FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id) ON UPDATE NO ACTION ON DELETE NO ACTION');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE adresse CHANGE lon `long` VARCHAR(255) DEFAULT NULL COLLATE utf8_general_ci');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale DROP FOREIGN KEY FK_AF220EF44DE7DC5C');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale DROP FOREIGN KEY FK_AF220EF4D5F8595C');
        $this->addSql('DROP INDEX idx_af220ef44de7dc5c ON adresse_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_9AC3772CC68BE09C ON adresse_has_ecole_doctorale (adresse_id)');
        $this->addSql('DROP INDEX idx_af220ef4d5f8595c ON adresse_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_9AC3772CBAB47356 ON adresse_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale ADD CONSTRAINT FK_AF220EF44DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
        $this->addSql('ALTER TABLE adresse_has_ecole_doctorale ADD CONSTRAINT FK_AF220EF4D5F8595C FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE adresse_has_etablissement DROP FOREIGN KEY FK_5BDC72294DE7DC5C');
        $this->addSql('ALTER TABLE adresse_has_etablissement DROP FOREIGN KEY FK_5BDC7229FF631228');
        $this->addSql('DROP INDEX idx_5bdc72294de7dc5c ON adresse_has_etablissement');
        $this->addSql('CREATE INDEX IDX_DB9F843DC68BE09C ON adresse_has_etablissement (adresse_id)');
        $this->addSql('DROP INDEX idx_5bdc7229ff631228 ON adresse_has_etablissement');
        $this->addSql('CREATE INDEX IDX_DB9F843DFF631228 ON adresse_has_etablissement (etablissement_id)');
        $this->addSql('ALTER TABLE adresse_has_etablissement ADD CONSTRAINT FK_5BDC72294DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
        $this->addSql('ALTER TABLE adresse_has_etablissement ADD CONSTRAINT FK_5BDC7229FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (etablissement_id)');
        $this->addSql('ALTER TABLE adresse_has_formation DROP FOREIGN KEY FK_7C62D8654DE7DC5C');
        $this->addSql('ALTER TABLE adresse_has_formation DROP FOREIGN KEY FK_7C62D8655200282E');
        $this->addSql('DROP INDEX idx_7c62d8654de7dc5c ON adresse_has_formation');
        $this->addSql('CREATE INDEX IDX_1B027D9FC68BE09C ON adresse_has_formation (adresse_id)');
        $this->addSql('DROP INDEX idx_7c62d8655200282e ON adresse_has_formation');
        $this->addSql('CREATE INDEX IDX_1B027D9F5200282E ON adresse_has_formation (formation_id)');
        $this->addSql('ALTER TABLE adresse_has_formation ADD CONSTRAINT FK_7C62D8654DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
        $this->addSql('ALTER TABLE adresse_has_formation ADD CONSTRAINT FK_7C62D8655200282E FOREIGN KEY (formation_id) REFERENCES formation (formation_id)');
        $this->addSql('ALTER TABLE adresse_has_laboratoire DROP FOREIGN KEY FK_7B1B58CC4DE7DC5C');
        $this->addSql('ALTER TABLE adresse_has_laboratoire DROP FOREIGN KEY FK_7B1B58CC76E2617B');
        $this->addSql('DROP INDEX idx_7b1b58cc4de7dc5c ON adresse_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_478CFF80C68BE09C ON adresse_has_laboratoire (adresse_id)');
        $this->addSql('DROP INDEX idx_7b1b58cc76e2617b ON adresse_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_478CFF80B65FA4A ON adresse_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE adresse_has_laboratoire ADD CONSTRAINT FK_7B1B58CC4DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
        $this->addSql('ALTER TABLE adresse_has_laboratoire ADD CONSTRAINT FK_7B1B58CC76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE adresse_has_ufr DROP FOREIGN KEY FK_BA094DFD4DE7DC5C');
        $this->addSql('ALTER TABLE adresse_has_ufr DROP FOREIGN KEY FK_BA094DFDA469CB09');
        $this->addSql('DROP INDEX idx_ba094dfd4de7dc5c ON adresse_has_ufr');
        $this->addSql('CREATE INDEX IDX_705B91FBC68BE09C ON adresse_has_ufr (adresse_id)');
        $this->addSql('DROP INDEX idx_ba094dfda469cb09 ON adresse_has_ufr');
        $this->addSql('CREATE INDEX IDX_705B91FBA469CB09 ON adresse_has_ufr (ufr_id)');
        $this->addSql('ALTER TABLE adresse_has_ufr ADD CONSTRAINT FK_BA094DFD4DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
        $this->addSql('ALTER TABLE adresse_has_ufr ADD CONSTRAINT FK_BA094DFDA469CB09 FOREIGN KEY (ufr_id) REFERENCES ufr (ufr_id)');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale DROP FOREIGN KEY FK_A39BB523A5522701');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale DROP FOREIGN KEY FK_A39BB523D5F8595C');
        $this->addSql('DROP INDEX idx_a39bb523a5522701 ON discipline_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_C5488024A5522701 ON discipline_has_ecole_doctorale (discipline_id)');
        $this->addSql('DROP INDEX idx_a39bb523d5f8595c ON discipline_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_C5488024BAB47356 ON discipline_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale ADD CONSTRAINT FK_A39BB523A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE discipline_has_ecole_doctorale ADD CONSTRAINT FK_A39BB523D5F8595C FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE discipline_has_laboratoire DROP FOREIGN KEY FK_A4BDA9DA5522701');
        $this->addSql('ALTER TABLE discipline_has_laboratoire DROP FOREIGN KEY FK_A4BDA9D76E2617B');
        $this->addSql('DROP INDEX idx_a4bda9da5522701 ON discipline_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_AC8C4DBCA5522701 ON discipline_has_laboratoire (discipline_id)');
        $this->addSql('DROP INDEX idx_a4bda9d76e2617b ON discipline_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_AC8C4DBCB65FA4A ON discipline_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE discipline_has_laboratoire ADD CONSTRAINT FK_A4BDA9DA5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE discipline_has_laboratoire ADD CONSTRAINT FK_A4BDA9D76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire DROP FOREIGN KEY FK_6C0DB82C76E2617B');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire DROP FOREIGN KEY FK_6C0DB82CD5F8595C');
        $this->addSql('DROP INDEX idx_6c0db82c76e2617b ON ecole_doctorale_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_94FAE651B65FA4A ON ecole_doctorale_has_laboratoire (laboratoire_id)');
        $this->addSql('DROP INDEX idx_6c0db82cd5f8595c ON ecole_doctorale_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_94FAE651BAB47356 ON ecole_doctorale_has_laboratoire (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire ADD CONSTRAINT FK_6C0DB82C76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE ecole_doctorale_has_laboratoire ADD CONSTRAINT FK_6C0DB82CD5F8595C FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale DROP FOREIGN KEY FK_E7AFF0CEFF631228');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale DROP FOREIGN KEY FK_E7AFF0CED5F8595C');
        $this->addSql('DROP INDEX idx_e7aff0ceff631228 ON etablissement_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_7731F8B3FF631228 ON etablissement_has_ecole_doctorale (etablissement_id)');
        $this->addSql('DROP INDEX idx_e7aff0ced5f8595c ON etablissement_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_7731F8B3BAB47356 ON etablissement_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale ADD CONSTRAINT FK_E7AFF0CEFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (etablissement_id)');
        $this->addSql('ALTER TABLE etablissement_has_ecole_doctorale ADD CONSTRAINT FK_E7AFF0CED5F8595C FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire DROP FOREIGN KEY FK_F5F858C9FF631228');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire DROP FOREIGN KEY FK_F5F858C976E2617B');
        $this->addSql('DROP INDEX idx_f5f858c9ff631228 ON etablissement_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_CC521A16FF631228 ON etablissement_has_laboratoire (etablissement_id)');
        $this->addSql('DROP INDEX idx_f5f858c976e2617b ON etablissement_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_CC521A16B65FA4A ON etablissement_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire ADD CONSTRAINT FK_F5F858C9FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (etablissement_id)');
        $this->addSql('ALTER TABLE etablissement_has_laboratoire ADD CONSTRAINT FK_F5F858C976E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire DROP FOREIGN KEY FK_C4AD03C39C347F1C');
        $this->addSql('DROP INDEX idx_c4ad03c39c347f1c ON laboratoire');
        $this->addSql('CREATE INDEX IDX_9367435C9C347F1C ON laboratoire (type_thesaurus)');
        $this->addSql('ALTER TABLE laboratoire ADD CONSTRAINT FK_C4AD03C39C347F1C FOREIGN KEY (type_thesaurus) REFERENCES thesaurus (thesaurus_id)');
        $this->addSql('ALTER TABLE laboratoire_has_axe DROP FOREIGN KEY FK_5034B4C976E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_axe DROP FOREIGN KEY FK_5034B4C92E30CD41');
        $this->addSql('DROP INDEX idx_5034b4c976e2617b ON laboratoire_has_axe');
        $this->addSql('CREATE INDEX IDX_D8DF49E4B65FA4A ON laboratoire_has_axe (laboratoire_id)');
        $this->addSql('DROP INDEX idx_5034b4c92e30cd41 ON laboratoire_has_axe');
        $this->addSql('CREATE INDEX IDX_D8DF49E42E30CD41 ON laboratoire_has_axe (axe_id)');
        $this->addSql('ALTER TABLE laboratoire_has_axe ADD CONSTRAINT FK_5034B4C976E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_axe ADD CONSTRAINT FK_5034B4C92E30CD41 FOREIGN KEY (axe_id) REFERENCES axe (axe_id)');
        $this->addSql('ALTER TABLE laboratoire_has_cnu DROP FOREIGN KEY FK_529FC51476E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_cnu DROP FOREIGN KEY FK_529FC514A5522701');
        $this->addSql('DROP INDEX idx_529fc51476e2617b ON laboratoire_has_cnu');
        $this->addSql('CREATE INDEX IDX_DA743839B65FA4A ON laboratoire_has_cnu (laboratoire_id)');
        $this->addSql('DROP INDEX idx_529fc514a5522701 ON laboratoire_has_cnu');
        $this->addSql('CREATE INDEX IDX_DA743839A5522701 ON laboratoire_has_cnu (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_cnu ADD CONSTRAINT FK_529FC51476E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_cnu ADD CONSTRAINT FK_529FC514A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_equipement DROP FOREIGN KEY FK_6C754B7876E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_equipement DROP FOREIGN KEY FK_6C754B78806F0F5C');
        $this->addSql('DROP INDEX idx_6c754b7876e2617b ON laboratoire_has_equipement');
        $this->addSql('CREATE INDEX IDX_1CFA71F9B65FA4A ON laboratoire_has_equipement (laboratoire_id)');
        $this->addSql('DROP INDEX idx_6c754b78806f0f5c ON laboratoire_has_equipement');
        $this->addSql('CREATE INDEX IDX_1CFA71F9806F0F5C ON laboratoire_has_equipement (equipement_id)');
        $this->addSql('ALTER TABLE laboratoire_has_equipement ADD CONSTRAINT FK_6C754B7876E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_equipement ADD CONSTRAINT FK_6C754B78806F0F5C FOREIGN KEY (equipement_id) REFERENCES equipement (equipement_id)');
        $this->addSql('ALTER TABLE laboratoire_has_formation DROP FOREIGN KEY FK_3AFD48DC76E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_formation DROP FOREIGN KEY FK_3AFD48DC5200282E');
        $this->addSql('DROP INDEX idx_3afd48dc76e2617b ON laboratoire_has_formation');
        $this->addSql('CREATE INDEX IDX_DF3346D9B65FA4A ON laboratoire_has_formation (laboratoire_id)');
        $this->addSql('DROP INDEX idx_3afd48dc5200282e ON laboratoire_has_formation');
        $this->addSql('CREATE INDEX IDX_DF3346D95200282E ON laboratoire_has_formation (formation_id)');
        $this->addSql('ALTER TABLE laboratoire_has_formation ADD CONSTRAINT FK_3AFD48DC76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_formation ADD CONSTRAINT FK_3AFD48DC5200282E FOREIGN KEY (formation_id) REFERENCES formation (formation_id)');
        $this->addSql('ALTER TABLE laboratoire_has_hceres DROP FOREIGN KEY FK_76EE1F8576E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_hceres DROP FOREIGN KEY FK_76EE1F85A5522701');
        $this->addSql('DROP INDEX idx_76ee1f8576e2617b ON laboratoire_has_hceres');
        $this->addSql('CREATE INDEX IDX_D0B16EBEB65FA4A ON laboratoire_has_hceres (laboratoire_id)');
        $this->addSql('DROP INDEX idx_76ee1f85a5522701 ON laboratoire_has_hceres');
        $this->addSql('CREATE INDEX IDX_D0B16EBEA5522701 ON laboratoire_has_hceres (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_hceres ADD CONSTRAINT FK_76EE1F8576E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_hceres ADD CONSTRAINT FK_76EE1F85A5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_sise DROP FOREIGN KEY FK_F65ED77E76E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_sise DROP FOREIGN KEY FK_F65ED77EA5522701');
        $this->addSql('DROP INDEX idx_f65ed77e76e2617b ON laboratoire_has_sise');
        $this->addSql('CREATE INDEX IDX_B30960F6B65FA4A ON laboratoire_has_sise (laboratoire_id)');
        $this->addSql('DROP INDEX idx_f65ed77ea5522701 ON laboratoire_has_sise');
        $this->addSql('CREATE INDEX IDX_B30960F6A5522701 ON laboratoire_has_sise (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_sise ADD CONSTRAINT FK_F65ED77E76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_sise ADD CONSTRAINT FK_F65ED77EA5522701 FOREIGN KEY (discipline_id) REFERENCES discipline (discipline_id)');
        $this->addSql('ALTER TABLE laboratoire_has_tag DROP FOREIGN KEY FK_3FD71D6676E2617B');
        $this->addSql('ALTER TABLE laboratoire_has_tag DROP FOREIGN KEY FK_3FD71D66BAD26311');
        $this->addSql('DROP INDEX idx_3fd71d6676e2617b ON laboratoire_has_tag');
        $this->addSql('CREATE INDEX IDX_B73CE04BB65FA4A ON laboratoire_has_tag (laboratoire_id)');
        $this->addSql('DROP INDEX idx_3fd71d66bad26311 ON laboratoire_has_tag');
        $this->addSql('CREATE INDEX IDX_B73CE04BBAD26311 ON laboratoire_has_tag (tag_id)');
        $this->addSql('ALTER TABLE laboratoire_has_tag ADD CONSTRAINT FK_3FD71D6676E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_tag ADD CONSTRAINT FK_3FD71D66BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (tag_id)');
        $this->addSql('ALTER TABLE laboratoire_has_theme DROP FOREIGN KEY FK_827F960976E2617B');
        $this->addSql('DROP INDEX idx_827f960976e2617b ON laboratoire_has_theme');
        $this->addSql('CREATE INDEX IDX_827F9609B65FA4A ON laboratoire_has_theme (laboratoire_id)');
        $this->addSql('ALTER TABLE laboratoire_has_theme ADD CONSTRAINT FK_827F960976E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE participant_has_axe DROP FOREIGN KEY FK_C2A78CDE9D1C3019');
        $this->addSql('ALTER TABLE participant_has_axe DROP FOREIGN KEY FK_C2A78CDE2E30CD41');
        $this->addSql('DROP INDEX idx_c2a78cde9d1c3019 ON participant_has_axe');
        $this->addSql('CREATE INDEX IDX_EA8D416B6A99F74A ON participant_has_axe (participant_id)');
        $this->addSql('DROP INDEX idx_c2a78cde2e30cd41 ON participant_has_axe');
        $this->addSql('CREATE INDEX IDX_EA8D416B2E30CD41 ON participant_has_axe (axe_id)');
        $this->addSql('ALTER TABLE participant_has_axe ADD CONSTRAINT FK_C2A78CDE9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_axe ADD CONSTRAINT FK_C2A78CDE2E30CD41 FOREIGN KEY (axe_id) REFERENCES axe (axe_id)');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale DROP FOREIGN KEY FK_F6039CA19D1C3019');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale DROP FOREIGN KEY FK_F6039CA1D5F8595C');
        $this->addSql('DROP INDEX idx_f6039ca19d1c3019 ON participant_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_2701BB8C6A99F74A ON participant_has_ecole_doctorale (participant_id)');
        $this->addSql('DROP INDEX idx_f6039ca1d5f8595c ON participant_has_ecole_doctorale');
        $this->addSql('CREATE INDEX IDX_2701BB8CBAB47356 ON participant_has_ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale ADD CONSTRAINT FK_F6039CA19D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_ecole_doctorale ADD CONSTRAINT FK_F6039CA1D5F8595C FOREIGN KEY (ecole_doctorale_id) REFERENCES ecole_doctorale (ecole_doctorale_id)');
        $this->addSql('ALTER TABLE participant_has_formation DROP FOREIGN KEY FK_E41DAB6C5200282E');
        $this->addSql('ALTER TABLE participant_has_formation DROP FOREIGN KEY FK_E41DAB6C9D1C3019');
        $this->addSql('DROP INDEX idx_e41dab6c9d1c3019 ON participant_has_formation');
        $this->addSql('CREATE INDEX IDX_464E5DC26A99F74A ON participant_has_formation (participant_id)');
        $this->addSql('DROP INDEX idx_e41dab6c5200282e ON participant_has_formation');
        $this->addSql('CREATE INDEX IDX_464E5DC25200282E ON participant_has_formation (formation_id)');
        $this->addSql('ALTER TABLE participant_has_formation ADD CONSTRAINT FK_E41DAB6C5200282E FOREIGN KEY (formation_id) REFERENCES formation (formation_id)');
        $this->addSql('ALTER TABLE participant_has_formation ADD CONSTRAINT FK_E41DAB6C9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_laboratoire DROP FOREIGN KEY FK_63D55B7C76E2617B');
        $this->addSql('ALTER TABLE participant_has_laboratoire DROP FOREIGN KEY FK_63D55B7C9D1C3019');
        $this->addSql('DROP INDEX idx_63d55b7c9d1c3019 ON participant_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_7B5970306A99F74A ON participant_has_laboratoire (participant_id)');
        $this->addSql('DROP INDEX idx_63d55b7c76e2617b ON participant_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_7B597030B65FA4A ON participant_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE participant_has_laboratoire ADD CONSTRAINT FK_63D55B7C76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE participant_has_laboratoire ADD CONSTRAINT FK_63D55B7C9D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_tag DROP FOREIGN KEY FK_AD4425719D1C3019');
        $this->addSql('ALTER TABLE participant_has_tag DROP FOREIGN KEY FK_AD442571BAD26311');
        $this->addSql('DROP INDEX idx_ad4425719d1c3019 ON participant_has_tag');
        $this->addSql('CREATE INDEX IDX_856EE8C46A99F74A ON participant_has_tag (participant_id)');
        $this->addSql('DROP INDEX idx_ad442571bad26311 ON participant_has_tag');
        $this->addSql('CREATE INDEX IDX_856EE8C4BAD26311 ON participant_has_tag (tag_id)');
        $this->addSql('ALTER TABLE participant_has_tag ADD CONSTRAINT FK_AD4425719D1C3019 FOREIGN KEY (participant_id) REFERENCES participant (participant_id)');
        $this->addSql('ALTER TABLE participant_has_tag ADD CONSTRAINT FK_AD442571BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (tag_id)');
        $this->addSql('ALTER TABLE ufr_has_laboratoire DROP FOREIGN KEY FK_F95EE0FFA469CB09');
        $this->addSql('ALTER TABLE ufr_has_laboratoire DROP FOREIGN KEY FK_F95EE0FF76E2617B');
        $this->addSql('DROP INDEX idx_f95ee0ffa469cb09 ON ufr_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_8B13F098A469CB09 ON ufr_has_laboratoire (ufr_id)');
        $this->addSql('DROP INDEX idx_f95ee0ff76e2617b ON ufr_has_laboratoire');
        $this->addSql('CREATE INDEX IDX_8B13F098B65FA4A ON ufr_has_laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE ufr_has_laboratoire ADD CONSTRAINT FK_F95EE0FFA469CB09 FOREIGN KEY (ufr_id) REFERENCES ufr (ufr_id)');
        $this->addSql('ALTER TABLE ufr_has_laboratoire ADD CONSTRAINT FK_F95EE0FF76E2617B FOREIGN KEY (laboratoire_id) REFERENCES laboratoire (laboratoire_id)');
        $this->addSql('ALTER TABLE valorisation DROP FOREIGN KEY FK_5B7243124DE7DC5C');
        $this->addSql('DROP INDEX fk_valorisation_localisation1_idx ON valorisation');
        $this->addSql('CREATE INDEX fk_valorisation_adresse1_idx ON valorisation (adresse_id)');
        $this->addSql('ALTER TABLE valorisation ADD CONSTRAINT FK_5B7243124DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (adresse_id)');
    }
}
